### ISSUE TITLE
Lab Report 1 Grading

### ISSUE THREAD

**Issue by akanksha-maker-ucsd** [ocboogie/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [ ] All screenshots correspond to the described steps
 - include screenshots for the following sections: Running Some Commands, Copying Files to the Host, SSH Keys, Getting Clever with SSH 
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good Job! I love how your pages site looks and the detail each section goes into. 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by ocboogie** [comment]
I submitted a regrade request a couple of days ago and wasn't sure if I was supposed to comment here... so here it is. 🎉
